# Generated by Django 5.2.3 on 2025-06-19 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_customer_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('lid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tid',
            new_name='lid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.CharField(default='112233', max_length=10),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('lid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='buyers.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
