# Generated by Django 5.2.3 on 2025-06-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_category_rename_create_at_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='lid',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lid',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lid',
            new_name='tid',
        ),
    ]
