# Generated by Django 5.2.3 on 2025-06-20 05:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_rename_lid_category_tid_rename_lid_customer_tid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
