# Generated by Django 5.2.3 on 2025-06-23 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0006_contactmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='buyers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
