# Generated by Django 5.2.3 on 2025-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0008_alter_cart_tid_alter_category_tid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
