# Generated by Django 5.2.3 on 2025-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0009_order_delivery_date_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
